version: '3'

services:
  torus-passwordless-auth:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3042:3042/tcp"
    volumes:
      - .:/app
