version: '3'

services:
  openlogin-password-manager:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.development
    ports:
      - "3042:3042/tcp"
    volumes:
      - .:/app
